### ISSUE TITLE
Tokenizer causes MemoryError on Windows 32bit

### ISSUE THREAD

**Issue by icoxfog417** [mocobeta/janome#19]
On the Windows 32bit environment, `Tokenizer` causes the `MemoryError` exception.

* Installation is successful.
* But below codes cause MemoryError

```pycon
from janome.tokenizer import Tokenizer
t = Tokenizer()

>>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\path\to\venv\lib\site-packages\janome\tokenizer.py", line 49, in __init__
    from sysdic import SYS_DIC
  File "C:\path\to\venv\lib\site-packages\sysdic\__init__.py", line 6, in <module>
    from . import entries, connections, chardef, unknowns
MemoryError
```

On the Windows 64bit, there is no error.
(I tested `janome` on Windows7 32bit and Windows8.1 64bit).

**Comment by mocobeta** [comment]
Thanks reporting, this is a known issue. 
Currently Janome does not support 32bit python environment, please use 64bit OS and 64bit Python. 

I was slightly surprised you can install janome on 32bit Python.
In my environment, Windows 7 (64bit) and Python 32bit, Installing is failed at install time because of  OOME. 

Anyway, 32bit support (i.e. optimize dictionary size and reduce memory required at install time) is an open issue.

**Comment by icoxfog417** [comment]
Thank you for the reply. 
I have known `janome` [doesn't support 32bit](http://mocobeta.github.io/janome/), so I thought that it was strange too.
(On the 32bit environment, initializing the `Tokenizer` takes many memory like the installing. So there may be something wrong.)

Anyway, taking huge memory makes it difficult to use `janome` on Amazon EC2 (micro) or Heroku.
So I hope this problem will be fixed (I also try to do it!).

**Comment by mocobeta** [comment]
I've released v0.2.6 that supports 32bit environments.
Please refer to updated documentation: http://mocobeta.github.io/janome/
I've not tried yet, but it also should be able to be installed on EC2 small instances (2GB RAM.)

Comments or reports are always welcome.

**Comment by icoxfog417** [comment]
@mocobeta 
I confirmed janome `0.2.6` works fine on 32bit Windows.
Thank you for your great update!

**Comment by mocobeta** [comment]
@icoxfog417 Thanks for your confirmation!
