### ISSUE TITLE
AWS EC2上でインストール出来ない

### ISSUE THREAD

**Issue by kenzotakahashi** [mocobeta/janome#26]
ローカルのMac OSでは問題なく動くのですが、AWSのlinuxにデプロイしようとしたところインストールされてない事が判明しました。サーバー上に入って手動でインストールしてみたら以下のエラーが出ました。

python3でpyenv使ってます。

$ pip install janome
Collecting janome
  Downloading Janome-0.2.8.tar.gz (13.6MB)
    100% |████████████████████████████████| 13.6MB 102kB/s
Building wheels for collected packages: janome
  Running setup.py bdist_wheel for janome ... done
  Stored in directory: /home/webmaster/.cache/pip/wheels/8b/08/f2/9e1d9300c6041925ad32148eb67bc997ec91f0d7ffc999573a
Successfully built janome
Installing collected packages: janome
/usr/local/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20: 19382 Killed                  "$PYENV_COMMAND_PATH" "$@"

**Comment by mocobeta** [comment]
報告ありがとうございます。
EC2でしょうか。もう少し詳しく、以下お知らせいただけますか？

* janomeをインストールした時だけ起こるエラー？（他のPythonパッケージをインストールした時は起こらない？）
* OSと、Pythonの詳しいバージョン

**Comment by kenzotakahashi** [comment]
これはjanomeをインストールした時だけ起きます。
OSはCentOSで、PythonはPython 3.5.1 |Anaconda 4.0.0です。

**Comment by mocobeta** [comment]
なるほど、ちなみにEC2のインスタンスタイプはどれをお使いでしょうか？
インストール時に500~600MBくらい使うので、やってみたことはないのですが, nanoやmicroインスタンスだと厳しい(OOMで死ぬ)かもしれないです。

**Comment by kenzotakahashi** [comment]
t2microです。なるほどそれが原因ですか。

**Comment by mocobeta** [comment]
OS, Pythonバージョンは問題ないはずなので、OOM Killerで殺されている可能性はありそうです。
small 以上だとインストールできるのは確認したことがあるので、もし可能でしたらインスタンスタイプを変更して試してみていただけると、メモリ不足が原因かどうか特定できると思います。

**Comment by kenzotakahashi** [comment]
インスタンスタイプをmediumにしたらいけました！ありがとうございます。

**Comment by mocobeta** [comment]
ご連絡ありがとうございます！
インストール時のメモリ使用量を削減するのは、すぐには対応できないので、今のところはすみませんが medium 以上をお使いいただくようにお願いします。
追って、ドキュメントのほうにも medium (RAM 2GB) 以上で、、、ということを追記しておきます。

原因がわかりましたので、このチケットはクローズとさせていただきますね。
また何かあれば再オープンをお願いします。
