### ISSUE TITLE
some missing reading/phonetic ?

### ISSUE THREAD

**Issue by bachnguyenhuu** [mocobeta/janome#47]
`就活	名詞,固有名詞,組織,*,*,*,就活,*,*`

I might be wrong but some words are missing phonetic/reading

**Comment by mocobeta** [comment]
"就活" is not included in the build-in dictionary Mecab-IPADIC, so janome cannot give reading or phonetic information to that.
For "unknown words", as it is called, please consider to use user dictionary.
