### ISSUE TITLE
Expected argument type for `POSStopFilter()` and `POSKeepFilter()` is unclear

### ISSUE THREAD

**Issue by nkmk** [mocobeta/janome#52]
Thanks for a great library!

It seems that `POSStopFilter()` and `POSKeepFilter()` don't expect `str`.

(v0.3.6)
```py
>>> from janome.analyzer import Analyzer
>>> from janome.tokenfilter import *
>>> 
>>> s = '吾輩は猫である'
>>> 
>>> a = Analyzer(token_filters=[POSKeepFilter(u'助動詞')])
>>> 
>>> for token in a.analyze(s):
...     print(token)
... 
は	助詞,係助詞,*,*,*,*,は,ハ,ワ
で	助動詞,*,*,*,特殊・ダ,連用形,だ,デ,デ
ある	助動詞,*,*,*,五段・ラ行アル,基本形,ある,アル,アル
>>> 
>>> a = Analyzer(token_filters=[POSKeepFilter([u'助動詞'])])
>>> 
>>> for token in a.analyze(s):
...     print(token)
... 
で	助動詞,*,*,*,特殊・ダ,連用形,だ,デ,デ
ある	助動詞,*,*,*,五段・ラ行アル,基本形,ある,アル,アル
```

If `str` is not expected, it's better to update example code in docs to avoid confusion.

- https://github.com/mocobeta/janome/blob/0.3.6/examples/usage_analyzer.py#L22

if `str` is expected, `tokenfilter.py` should be updated.

- https://github.com/mocobeta/janome/blob/0.3.6/janome/tokenfilter.py#L75
- https://github.com/mocobeta/janome/blob/0.3.6/janome/tokenfilter.py#L98

For example:

```py
self.pos_list = pos_list
```
->
```py
if type(pos_list) == str:
	self.pos_list = [pos_list]
else:
	self.pos_list = pos_list
```

**Comment by mocobeta** [comment]
Thank you for pointing it. I fixed `usage_analyzer.py` on the develop branch.
I like your second option (POSKeepFilter can take list or str,) it will come feature releases. PR is welcome of course!

**Comment by nkmk** [comment]
Thank you for the prompt response! I would be glad if you could update `tokenfilter.py` someday.

Please close this issue whenever you like.
