### ISSUE TITLE
Feature request: Anime-proof Japanese Morphology

### ISSUE THREAD

**Issue by DonaldTsang** [mocobeta/janome#59]
To be used along side https://github.com/zcyzcy88/TagTable and https://github.com/evazion/translate-pixiv-tags there should be a feature to add custom words into Janome to be more accurate for certain tasks

**Comment by mocobeta** [comment]
Janome provides general user defined dictionary feature to add custom words: https://mocobeta.github.io/janome/en/#how-to-use-with-user-defined-dictionary

If this is insufficient, can you please be more specific?

**Comment by DonaldTsang** [comment]
A tool that guides people on creating user defined dictionaries...

**Comment by mocobeta** [comment]
User defined dictionary is just simple CSV file, I'm not sure what kind of tool is needed (except for ordinary text editors) for that. If you have any thoughts on your mind, can you open an issue for that? Please be more specific.
