### ISSUE TITLE
Words defined in use_dictionary are not tokenized in input text

### ISSUE THREAD

**Issue by emadg** [mocobeta/janome#68]
I have a large set of samples with their correct form of tokenization. When the samples are tokenized by Janome, the tokenization is different from the expected way in my correct tokenizations. 

Many of the failing cases are when there are two consecutive Katakana words in my input, and Janome does not recognize them as two words and creates one token with two words attached together.

I collected the words and added them to the user defined dictionary in Simplified format. This corrected the tokenization of about half of my samples, but many of samples are still incorrectly tokenized including the many cases with consecutive Katakana words.

I tried to find a minimal example below which replicates my problem.

Please let me know if there something else I need to do to improve the tokenization and assure right tokenization for the words I added to user defined dictionary. Thanks :)

My environment:
* Windows 7
* Python 3.5
* No virtual environment, I am using a python interpreter directly installed on windows and installed Janome in it.
* Janome version 0.3.9

Minimal code replicating my problem:

from janome.tokenizer import Tokenizer as JanomeTokenizer

'''
defined words in test.csv:
コミミックス,カスタム名詞,コミミックス
シンクロナイズド,カスタム名詞,シンクロナイズド
ダイビング,カスタム名詞,ダイビング
'''

string = 'コミミックスシンクロナイズドダイビング'

tok = JanomeTokenizer('test.csv', udic_type='simpledic', udic_enc='utf8')
toks = tok.tokenize(string, wakati=True)
tlist = [ tok for tok in toks if tok != ' ' ]
print ('\n'.join(tlist))

**Comment by mocobeta** [comment]
I tested the code (on Windows 10, Python 3.6, janome is 0.3.9) and here is the result.

```
>>> from janome.tokenizer import Tokenizer as JanomeTokenizer
>>> string = 'コミミックスシンクロナイズドダイビング'
>>> tok = JanomeTokenizer('test.csv', udic_type='simpledic', udic_enc='utf8')
>>> toks = tok.tokenize(string, wakati=True)
>>> tlist = [ tok for tok in toks if tok != ' ' ]
>>> print ('\n'.join(tlist))
コミミックス
シンクロナイズド
ダイビング
```

The user dictionary works correctly for me, so I don't understand what's wrong with it. Can you please describe what is your expectation here? 
If the tokenization result above is different from yours, one possibility is wrong character encoding (`udic_enc`). Is the csv file surely encoded by utf8?
