### ISSUE TITLE
Can I know all the 品詞?

### ISSUE THREAD

**Issue by HeroadZ** [mocobeta/janome#71]
I want to make use of POSKeepFilter, but I don't know all the POS, where can I find it?

**Comment by mocobeta** [comment]
Janome uses "MeCab IPADIC" as the built-in dictionary that follows "IPA品詞体系".
The POS tags are listed here (in Japanese):
http://www.unixuser.org/~euske/doc/postag/#chasen

**Comment by mocobeta** [comment]
And here is the official manual of the dictionary format. This includes the description for each POS tag (in Japanese):
http://sils.shoin.ac.jp/~gunji/AI/Kyozai/ChaSen/ipadic-2.7.0-ja.pdf

**Comment by HeroadZ** [comment]
Thank you very much!!
