### ISSUE TITLE
Add version information into  ` __init__.py` 

### ISSUE THREAD

**Issue by norihitoishida** [mocobeta/janome#91]
Hello @mocobeta and janome-contributors !
Thank you for developing such a great library.

I am using `janome` in an interactive environment like jupyter-lab.

I'd be very happy if `janome.__version__` could show the version, like other major libraries (`Numpy`, `statsmodels`, `PyTorch`, `Optuna`, etc.). This could be achieved by modifying ` __init__.py`.

It would also be beneficial to import classes such as Tokenizer inside ` __init__.py`, so that the `dir(janome)` shows what classes are below it.

However, this also has the disadvantage of increasing the time and memory usage of `import janome`.

What are the opinions of developers regarding the implementation of this?
If there are no problems, I would like to send a pull request.

Best regard.

**Comment by mocobeta** [comment]
Hi @norihitoishida,
I am not familiar with the `__version__` property. Can you point the specification/example for that, or make a patch?

FWIW, we already have `version.py` file that holds the version information and bundled `janome` command shows it by `--version` option. However I'm not against changing it if there's a standard way to manage the version info.
https://github.com/mocobeta/janome/commit/ee3855b6014477f18f6c39114f15a6d084a94c55#diff-e69d7a450d60cfdc99117b5a2647ac1aef831b92ee53a2f8b7e2f261be04ceec

**Comment by norihitoishida** [comment]
Thanks for the quick response @mocobeta !

PEP 8 and PEP 396 recommend the use of `__version__` property. 
As naive implementation, how about changing __init__.py like this?
```
from janome.version import JANOME_VERSION as __version__
```
```
>>> import janome
>>> janome.__version__
'0.3.10'
```

### Reference
- [PEP 8](https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names)
- [PEP 396](https://www.python.org/dev/peps/pep-0396/) 
- [note.nkmk.me Pythonのパッケージ（ライブラリ）のバージョンを確認](https://note.nkmk.me/python-package-version/)

### Examples
- [Optuna](https://github.com/optuna/optuna/blob/f65e66b9222c00e0d33e8f50398fef8045608f01/optuna/__init__.py#L27)
- [PyTorch](https://github.com/pytorch/pytorch/blob/c0deb231db76dbea8a9d326401417f7d1ce96ed5/torch/__init__.py#L24)
- [Numpy](https://github.com/numpy/numpy/blob/f7bc512184a1de3992b0d154e6244a7a0d9a574f/numpy/__init__.py#L398)
- [statsmodels](https://github.com/statsmodels/statsmodels/blob/bf912564824e5bf854d7c90c2eba059006d4471e/statsmodels/__init__.py#L36)

**Comment by mocobeta** [comment]
Thanks for the pointers,

> from janome.version import JANOME_VERSION as __version__

It sounds good to me (I don't think we need more complex implementations as libraries listed there)!

**Comment by norihitoishida** [comment]
Thank you so much :)
