### ISSUE TITLE
Added Conda download option

### ISSUE THREAD

**Issue by BastianZim** [mocobeta/janome#97]
Hi,

I just wanted to let everybody know that I added the package to [conda-forge](https://conda-forge.org), so that the package can also be downloaded using [conda](https://anaconda.org).

Repo: https://github.com/conda-forge/janome-feedstock
Anaconda: https://anaconda.org/conda-forge/janome

If there is interest, I can add a badge or install section to the readme, but I wanted to check here first if that is wanted.

Also, in case any of the maintainers would like to be added as maintainers to the Conda-forge repo, feel free to ping me here or add an issue/pr to the feedstock repo.

Thanks!

**Comment by mocobeta** [comment]
> If there is interest, I can add a badge or install section to the readme, but I wanted to check here first if that is wanted.

Thanks, this sounds good!

**Comment by BastianZim** [comment]
There are a couple of options for the badges, do you have a preference?

1) [![Conda](https://img.shields.io/conda/v/conda-forge/janome)](https://anaconda.org/conda-forge/janome) (Text can be modified)
2) [![Conda](https://img.shields.io/conda/dn/conda-forge/janome?label=Conda%20downloads)](https://anaconda.org/conda-forge/janome) (Text can be modified)

**Comment by mocobeta** [comment]
I'd prefer the first one (which includes version number), but both are okay for me :)

**Comment by BastianZim** [comment]
Ok perfect, will add a PR just now.

**Comment by mocobeta** [comment]
Just merged, thanks @BastianZim!

**Comment by BastianZim** [comment]
Pleasure! Thanks for merging it so quickly!
